name: Release Build on main push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create release build
        run: |
          mkdir -p build
          ./build_for_mac_linux.sh

      #      - name: Upload artifact
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: ffx.tools.DawProject.xrnx-${{ github.ref_name }}-${{ github.event.head_commit.message }}
      #          path: build/ffx.tools.DawProject.xrnx

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto-release-${{ github.run_number }}
          name: 'ffx.tools.DawProject.xrnx'
          body: 'DawProject ${{ github.ref_name }} (${{ github.event.head_commit.message }})'
          files: build/ffx.tools.DawProject.xrnx
